name: Run Tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Nextflow v22.10.4
        run: |
          wget https://github.com/nextflow-io/nextflow/releases/download/v22.10.4/nextflow
          sudo mv nextflow /usr/local/bin/

      - name: Test
        run: mvn install
